version: '3.8'
services:
  app:
    image: file-sharing-app
    container_name: file-sharing-app
    restart: always
    command: sh -c "npm install && npm start"
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
