name: Production Workflow
on:
  push:
    branches:
      - main
jobs:
  workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Running lint script
        run: npm run lint

      - name: Secret Variables
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          MY_DB_CONN_STRING: ${{ secrets.MY_DB_CONN_STRING }}
          MY_DB_NAME: ${{ secrets.MY_DB_NAME }}
          MY_USERS_COLLECTION_NAME: ${{ secrets.MY_USERS_COLLECTION_NAME }}
          MY_FILES_COLLECTION_NAME: ${{ secrets.MY_FILES_COLLECTION_NAME }}
        run: |
          echo "MY_SECRET_KEY: $MY_SECRET_KEY"
          echo "MY_DB_CONN_STRING: $MY_DB_CONN_STRING"
          echo "MY_DB_NAME: $MY_DB_NAME"
          echo "MY_USERS_COLLECTION_NAME: $MY_USERS_COLLECTION_NAME"
          echo "MY_FILES_COLLECTION_NAME: $MY_FILES_COLLECTION_NAME"
