name: Linting and Testing
on:
  push:
    branches:
      - main
jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Running lint script
        run: npm run lint

      - name: Testing script
        run: npm test
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
          MY_DB_CONN_STRING: ${{ secrets.MY_DB_CONN_STRING }}
          MY_DB_NAME: ${{ secrets.MY_DB_NAME }}
          MY_USERS_COLLECTION_NAME: ${{ secrets.MY_USERS_COLLECTION_NAME }}
          MY_FILES_COLLECTION_NAME: ${{ secrets.MY_FILES_COLLECTION_NAME }}
