name: Project Workflow
on:
  push:
    branches:
      - main
env:
  MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
  MY_DB_CONN_STRING: ${{ secrets.MY_DB_CONN_STRING }}
  MY_DB_NAME: ${{ secrets.MY_DB_NAME }}

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Running lint script
        run: npm run lint

      - name: Secret Variables
        run: |
          echo "MY_SECRET_KEY: $MY_SECRET_KEY"
          echo "MY_DB_CONN_STRING: $MY_DB_CONN_STRING"
          echo "MY_DB_NAME: $MY_DB_NAME"

      - name: Testing
        run: npm test
