name: Linting and Testing
on:
  push:
    branches:
      - main
jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Running lint script
        run: npm run lint

      - name: Set up environment variables
        run: |
          echo "MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}" >> $GITHUB_ENV
          echo "MY_DB_CONN_STRING: ${{ secrets.MY_DB_CONN_STRING }}" >> $GITHUB_ENV
          echo "MY_DB_NAME: ${{ secrets.MY_DB_NAME }}" >> $GITHUB_ENV
          echo "MY_USERS_COLLECTION_NAME: ${{ secrets.MY_USERS_COLLECTION_NAME }}" >> $GITHUB_ENV
          echo "MY_FILES_COLLECTION_NAME: ${{ secrets.MY_FILES_COLLECTION_NAME }}" >> $GITHUB_ENV

      - name: Testing script
        run: npm run test
